name: Playwright tescase 
on: 
    workflow_dispatch: 

jobs: 
    automation-test:
    runs-on: ubuntu-latest
    steps: 
    -name: test Login.spec.js
    run: npx playwright test ./Login.spec.js
    